### ISSUE TITLE
instance oss in pach 3.0 

### ISSUE THREAD

**Issue by kamila231993** [noisiver/mod-progression#6]
Hello we did 0 drakes.. they don t drop emblems of heroism... adds weren t hard to kill... not sure if that is normal or not... mini drakes were easy as well.
The big drake... had some bugs ... one side of the wall went always half to mid... we didnt need to avoid it. break of the drake wasn t that hard.

is ok ?
is it ok that's how it has to be?

**Comment by noisiver** [comment]
This isn't affected by this module. I haven't changed any of the encounters and I don't add/remove emblems from loot tables - I run update queries to change them, and that means I haven't removed emblems or even added emblems to things that normally doesn't have them. These issues are better reported to AzerothCore since it's completely unrelated to this module.

**Comment by noisiver** [comment]
I'll close this with the recommendation of reporting it to the official AzerothCore repository as again this is completely unrelated to this module.
